baseurl = "https://dfsaustralia.com/"
title = "Daily Fantasy Sports Australia"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-175567511-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 2
    
[[menu.main]]
    identifier = "menu.tools"
    name = "Tools"
    url  = "/img/tools.jpeg"
    weight = 3
    
[[menu.main]]
    name       = "Advanced (Draftstars)"
    identifier = "section.advanced"
    url        = ""
    weight     = 1
    parent     = "menu.tools"
    post       = 1
    
[[menu.main]]
    name       = "Profit Tracker"
    url        = "/profit-tracker/"
    weight     = 1
    parent     = "section.advanced"
    
[[menu.main]]
    name       = "Historical Tournaments"
    url        = "/historical-tournaments/"
    weight     = 2
    parent     = "section.advanced"

[[menu.main]]
    identifier = "menu.afl"
    name = "AFL"
    url  = "/img/afl-tools.jpeg"
    weight = 4
    
[[menu.main]]
    name       = "Breakdown Per Round"
    identifier = "section.afl.player.stats"
    url        = ""
    weight     = 1
    parent     = "menu.afl"
    post       = 1
    
[[menu.main]]
    name       = "Fantasy Points"
    url        = "/afl-fantasy-points/"
    weight     = 1
    parent     = "section.afl.player.stats"
    
[[menu.main]]
    name       = "Time on Ground"
    url        = "/afl-tog/"
    weight     = 2
    parent     = "section.afl.player.stats"
    
[[menu.main]]
    name       = "Centre Bounce Attendances"
    url        = "/afl-cbas/"
    weight     = 3
    parent     = "section.afl.player.stats"
    
[[menu.main]]
    name       = "Kick Ins"
    url        = "/afl-kickins/"
    weight     = 4
    parent     = "section.afl.player.stats"
    
[[menu.main]]
    name       = "Ruck Contests"
    url        = "/afl-ruck-contests/"
    weight     = 5
    parent     = "section.afl.player.stats"

[[menu.main]]
    name       = "Game Logs & Splits"
    identifier = "section.afl.player.logs"
    url        = ""
    weight     = 2
    parent     = "menu.afl"
    post       = 1
    
[[menu.main]]
    name       = "Player Stats"
    url        = "/afl-player-stats/"
    weight     = 1
    parent     = "section.afl.player.logs"

[[menu.main]]
    name       = "Daily Fantasy"
    identifier = "section.afl.daily.fantasy"
    url        = ""
    weight     = 1
    parent     = "menu.afl"
    post       = 2

[[menu.main]]
    name       = "Draftstars Slate Analysis"
    url        = "/afl-draftstars-slate-analysis/"
    weight     = 1
    parent     = "section.afl.daily.fantasy"

[[menu.main]]
    name       = "With/Without"
    url        = "/afl-with-without/"
    weight     = 2
    parent     = "section.afl.daily.fantasy"
    
[[menu.main]]
    name       = "Team Stacking"
    url        = "/afl-team-stacking/"
    weight     = 3
    parent     = "section.afl.daily.fantasy"    
    
[[menu.main]]
    name       = "Matchup History"
    url        = "/afl-matchup-history/"
    weight     = 4
    parent     = "section.afl.daily.fantasy"
    
[[menu.main]]
    name       = "Premium tools"
    identifier = "section.afl.premium.tools"
    url        = ""
    weight     = 2
    parent     = "menu.afl"
    post       = 2
    
[[menu.main]]
    name       = "Tournament Research"
    url        = "/afl-research/"
    weight     = 1
    parent     = "section.afl.premium.tools"

[[menu.main]]
    identifier = "menu.nfl"
    name = "NFL"
    url  = "/img/nfl-tools.jpeg"
    weight = 5
    
[[menu.main]]
    name       = "Offensive Stats"
    identifier = "section.nfl.player.stats"
    url        = ""
    weight     = 1
    parent     = "menu.nfl"
    post       = 1
    
[[menu.main]]
    name       = "Target Breakdown"
    url        = "/nfl-targets/"
    weight     = 1
    parent     = "section.nfl.player.stats"
    
[[menu.main]]
    name       = "Rushing Breakdown"
    url        = "/nfl-rushing/"
    weight     = 2
    parent     = "section.nfl.player.stats"
    
[[menu.main]]
    name       = "Target Share"
    url        = "/nfl-target-share/"
    weight     = 3
    parent     = "section.nfl.player.stats"

[[menu.main]]
    name       = "Offensive Snaps"
    url        = "/nfl-offensive-snaps/"
    weight     = 4
    parent     = "section.nfl.player.stats"
    
[[menu.main]]
    name       = "Player Stats [NFL]"
    url        = "/nfl-player-stats/"
    weight     = 5
    parent     = "section.nfl.player.stats"
    
[[menu.main]]
    name       = "Daily Fantasy"
    identifier = "section.nfl.fantasy"
    url        = ""
    weight     = 1
    parent     = "menu.nfl"
    post       = 2
    
[[menu.main]]
    name       = "Slate Analysis [NFL] (COMING SOON)"
    url        = ""
    weight     = 1
    parent     = "section.nfl.fantasy"    

[[menu.main]]
    name       = "Defense vs Position"
    url        = "/nfl-dvp/"
    weight     = 2
    parent     = "section.nfl.fantasy"
    
[[menu.main]]
    name       = "Player Stacks"
    url        = "/nfl-stacks/"
    weight     = 3
    parent     = "section.nfl.fantasy"   
    
[[menu.main]]
    name       = "DST Trends (COMING SOON)"
    url        = ""
    weight     = 4
    parent     = "section.nfl.fantasy" 
    
[[menu.main]]
    name       = "Bookmakers"
    identifier = "section.nfl.bookmakers"
    url        = ""
    weight     = 2
    parent     = "menu.nfl"
    post       = 2
    
[[menu.main]]
    name       = "Game O/U & Lines [NFL]"
    url        = "/nfl-odds/"
    weight     = 1
    parent     = "section.nfl.bookmakers"  





[[menu.main]]
    identifier = "menu.nba"
    name = "NBA"
    url  = "/img/nba-tools.jpeg"
    weight = 6
    
[[menu.main]]
    name       = "Stats"
    identifier = "section.nba.player.stats"
    url        = ""
    weight     = 1
    parent     = "menu.nba"
    post       = 1

[[menu.main]]
    name       = "Usage Rate (COMING SOON)"
    url        = ""
    weight     = 1
    parent     = "section.nba.player.stats"
    
[[menu.main]]
    name       = "Player Stats [NBA]"
    url        = "/nba-player-stats/"
    weight     = 2
    parent     = "section.nba.player.stats"
    
[[menu.main]]
    name       = "Daily Fantasy"
    identifier = "section.nba.fantasy"
    url        = ""
    weight     = 1
    parent     = "menu.nba"
    post       = 2
    
[[menu.main]]
    name       = "Slate Analysis [NBA] (COMING SOON)"
    url        = ""
    weight     = 1
    parent     = "section.nba.fantasy"    

[[menu.main]]
    name       = "Defense vs Position (COMING SOON)"
    url        = ""
    weight     = 2
    parent     = "section.nba.fantasy"
    
[[menu.main]]
    name       = "With/Without Player Trends"
    url        = "/nba-with-without/"
    weight     = 3
    parent     = "section.nba.fantasy"   
    

    
[[menu.main]]
    name       = "Bookmakers"
    identifier = "section.nba.bookmakers"
    url        = ""
    weight     = 2
    parent     = "menu.nba"
    post       = 2
    
[[menu.main]]
    name       = "Game O/U & Lines [NBA]"
    url        = "/nba-odds/"
    weight     = 1
    parent     = "section.nba.bookmakers"  






[[menu.main]]
    identifier = "menu.golf"
    name = "Golf"
    url  = "/img/golf-tools.jpeg"
    weight = 7
    
[[menu.main]]
    name       = "Daily Fantasy"
    identifier = "section.golf.fantasy"
    url        = ""
    weight     = 1
    parent     = "menu.golf"
    post       = 1
    
[[menu.main]]
    name       = "Slate Analysis [GOLF]"
    url        = "/golf-slate-analysis/"
    weight     = 1
    parent     = "section.golf.fantasy"
    
[[menu.main]]
    name       = "Golfer Cuts"
    url        = "/golf-cuts/"
    weight     = 2
    parent     = "section.golf.fantasy"

#[[menu.main]]
#    identifier = "about"
  #  name = "About"
 #   url  = "/about/"
  #  weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/DFSAustralia"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/DFSAustralia"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

#[[menu.topbar]]
    #weight = 3
    #name = "Email"
    #url = "mailto:dailyfantasysportsaustralia@gmail.com"
    #pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Morts"
    defaultKeywords = ["AFL", "Fantasy Sports", "Daily Fantasy Sports","DFS","AFLDFS","DFSAustralia",
    "Draftstars","Lineup Cruncher","Moneyball","AFL Fantasy","Draftkings","DreamTeam","Fantasy Points"]
    mainSections = ["blog","data tools"]
    defaultDescription = "Daily Fantasy Sports Analytics and Data Applications"

    # Social media
    facebook_site = "DFSAustralia" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "DFSAustralia" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/stadium.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    #email = "dailyfantasysportsaustralia@gmail.com"
    #contact_form_ajax = false

    about_us = "<p>Daily Fantasy Sports Australia (DFSAustralia) have been providing data driven insights to the Australian DFS Community since 2016.</p>"
    copyright = "Copyright (c) 2016 - 2021, Daily Fantasy Sports Australia; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/stadium.png"
    logo_small = "img/stadium.png"
    #address = ""

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    #text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      #<p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      #<a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      #</p>
      #"""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = ""

[params.see_more] # This is where to add more buttons for more applications
    enable = true
    icon = "fas fa-tools"
    title = "Daily Fantasy Sports Applications?"
    subtitle = "We've got you covered with the most advanced Daily Fantasy Sports Tools available for Draftstars."


[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Recommended Sites"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""

[params.footer.recent_posts]
    enable = false
